# Site settings
title: "Valentine HERRMANN"
email: HerrmannV@si.edu
url: https://valentineherr.github.io
description: "This is my personal website. I am a research assisant at the Smithsonian Conservation Institute, in Front Royal, VA, USA."
keywords: "Valentine HERRMANN, Valentine, Herrmann, Research assistant, Data Management, Data Analysis, Capture Mark Recapture, Forest Ecology, Conservation Biology, ecology, Smithsonian"
skills: "Research Assistant - R scripts Developer - Data Management - Data Analysis"
meta_author: Herrmann Valentine

# enable Jekyll SEO tag plugin
plugins:
  - jekyll-seo-tag

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: afc474 #80B3FF
  primary-rgb: "175,196,116" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Valentine Herrmann
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
#  - title: twitter
#    url: http://twitter.com/jekyllrb
#  - title: facebook
#    url:
  - title: stack-overflow
    url: https://stackoverflow.com/users/7254069/valentine
#  - title: bitbucket
#    url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/ValentineHerr
  - title: google
    url: https://scholar.google.fr/citations?user=oPO7Zz0AAAAJ&hl=fr
  - title: linkedin
    url : https://www.linkedin.com/in/valentine-herrmann-ab6a0474/

# Postal address (add as many lines as necessary)
address:
  - line: 1500 remount Road
  - line: Front Royal, VA 20106

# Credits content
credits: 'This website was built off of the free to use, open source Bootstrap theme <strong>Freelancer</strong> created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
